// ============================================================================
// Team crests from Football-Data.org — replaces flag emojis on the squads /
// standings / live pages with the real federation badge.
//
// Regenerated by `npx tsx scripts/sync-fd-extras.ts crests`. Hand-written
// entries fill gaps for codes Football-Data uses (e.g. CHE) that differ from
// the FIFA TLA we use elsewhere — see normalizeFdCrestKey().
// ============================================================================

import data from "@/lib/tournament/fd-crests.json";

interface CrestData {
  syncedAt: string;
  crests: Record<string, { name: string; crest: string; id: number }>;
}

const TYPED = data as CrestData;

/**
 * Football-Data sometimes returns slightly different 3-letter codes than the
 * FIFA TLA we use. Map them so a lookup with our code (e.g. "SUI" / "RSA")
 * still resolves to the crest FD stored under "CHE" / "ZAF".
 */
const ALIAS: Record<string, string> = {
  SUI: "CHE",   // Switzerland
  RSA: "ZAF",   // South Africa
  KSA: "SAU",   // Saudi Arabia
  CUR: "CUW",   // Curaçao
  HAI: "HTI",   // Haiti
  GER: "DEU",   // Germany
  POR: "PRT",   // Portugal
  CRO: "HRV",   // Croatia
  NED: "NLD",   // Netherlands
  URU: "URY",   // Uruguay
  PAR: "PRY",   // Paraguay
  ALG: "DZA",   // Algeria
};

export function getTeamCrest(code: string | null | undefined): string | null {
  if (!code) return null;
  const upper = code.toUpperCase();
  return TYPED.crests[upper]?.crest ?? TYPED.crests[ALIAS[upper] || ""]?.crest ?? null;
}

export function getCrestsSyncedAt(): string {
  return TYPED.syncedAt;
}
