// ============================================================================
// WC2026 — Official squad status per national team
// Source: https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads
// The OFFICIAL_SQUADS map and LAST_SYNC are regenerated by
// `npx tsx scripts/sync-official-squads.ts`. Helpers below the sentinel are
// hand-written and preserved across re-syncs.
// ============================================================================

export type OfficialState = "announced" | "fifa_confirmed";

export interface OfficialStatus {
  state: OfficialState;
  announcedAt: string; // ISO date — when the federation published their final 26
  confirmedAt?: string; // ISO date — when FIFA certified (June 2, 2026 onward)
  source: string; // Wikipedia section URL
}

// <generated-start> — do not edit between these sentinels; regenerated by the scraper.
export const OFFICIAL_SQUADS: Record<string, OfficialStatus> = {
  AUT: {
    state: "announced",
    announcedAt: "2026-05-18",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Austria",
  },
  BEL: {
    state: "announced",
    announcedAt: "2026-05-15",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Belgium",
  },
  BIH: {
    state: "announced",
    announcedAt: "2026-05-11",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Bosnia_and_Herzegovina",
  },
  BRA: {
    state: "announced",
    announcedAt: "2026-05-18",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Brazil",
  },
  CIV: {
    state: "announced",
    announcedAt: "2026-05-15",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Ivory_Coast",
  },
  COD: {
    state: "announced",
    announcedAt: "2026-05-18",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#DR_Congo",
  },
  CPV: {
    state: "announced",
    announcedAt: "2026-05-18",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Cape_Verde",
  },
  CRO: {
    state: "announced",
    announcedAt: "2026-05-18",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Croatia",
  },
  CUR: {
    state: "announced",
    announcedAt: "2026-05-18",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Curaçao",
  },
  FRA: {
    state: "announced",
    announcedAt: "2026-05-14",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#France",
  },
  HAI: {
    state: "announced",
    announcedAt: "2026-05-15",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Haiti",
  },
  JPN: {
    state: "announced",
    announcedAt: "2026-05-15",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Japan",
  },
  KOR: {
    state: "announced",
    announcedAt: "2026-05-16",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#South_Korea",
  },
  NZL: {
    state: "announced",
    announcedAt: "2026-05-14",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#New_Zealand",
  },
  SCO: {
    state: "announced",
    announcedAt: "2026-05-19",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Scotland",
  },
  SWE: {
    state: "announced",
    announcedAt: "2026-05-12",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Sweden",
  },
  TUN: {
    state: "announced",
    announcedAt: "2026-05-15",
    source: "https://en.wikipedia.org/wiki/2026_FIFA_World_Cup_squads#Tunisia",
  },
};
export const LAST_SYNC: string | null = "2026-05-19T12:32:40.556Z";
// <generated-end>

export function getOfficialStatus(code: string): OfficialStatus | null {
  return OFFICIAL_SQUADS[code] ?? null;
}

export function isOfficiallyAnnounced(code: string): boolean {
  const s = OFFICIAL_SQUADS[code];
  return s?.state === "announced" || s?.state === "fifa_confirmed";
}

export function isFifaConfirmed(code: string): boolean {
  return OFFICIAL_SQUADS[code]?.state === "fifa_confirmed";
}
