/**
 * Squad Update Script — Fetches all 48 WC2026 team squads from API-Football
 * Run: npx tsx scripts/update-squads.ts
 *
 * Uses API-Football (api-sports.io) free tier — 100 requests/day
 * All 48 teams = 48 requests, safe within limits
 */

import * as fs from "fs";
import * as path from "path";

const API_KEY = process.env.API_FOOTBALL_KEY || "bf9c9c08ac73c3896876105278ea7a2c";
const API_HOST = "v3.football.api-sports.io";

// Verified API-Football national team IDs (from direct API search)
const TEAM_IDS: Record<string, number> = {
  // Group A
  MEX: 16, KOR: 17, CZE: 770, RSA: 1531,
  // Group B
  CAN: 5529, QAT: 1569, SUI: 15, BIH: 776,
  // Group C
  BRA: 6, MAR: 31, SCO: 1108, HAI: 1536,
  // Group D
  USA: 2384, PAR: 2380, TUR: 777, AUS: 20,
  // Group E
  GER: 25, ECU: 2382, CIV: 1532, CUR: 5531,
  // Group F
  NED: 1118, JPN: 12, SWE: 1104, TUN: 1533,
  // Group G
  BEL: 1, IRN: 22, EGY: 32, NZL: 4673,
  // Group H
  ESP: 9, URU: 7, KSA: 23, CPV: 1534,
  // Group I
  FRA: 2, SEN: 13, NOR: 1106, IRQ: 1570,
  // Group J
  ARG: 26, AUT: 775, ALG: 1530, JOR: 1564,
  // Group K
  POR: 27, COL: 8, UZB: 1572, COD: 1535,
  // Group L
  ENG: 10, CRO: 3, GHA: 1534, PAN: 11,
};

// Hebrew names for position mapping
const POS_MAP: Record<string, "GK" | "DEF" | "MID" | "FW"> = {
  Goalkeeper: "GK",
  Defender: "DEF",
  Midfielder: "MID",
  Attacker: "FW",
};

interface ApiPlayer {
  id: number;
  name: string;
  age: number;
  number: number | null;
  position: string;
  photo: string;
}

interface ApiSquadResponse {
  response: {
    team: { id: number; name: string; logo: string };
    players: ApiPlayer[];
  }[];
}

async function fetchSquad(teamId: number): Promise<{ players: ApiPlayer[]; logo?: string }> {
  const url = `https://${API_HOST}/players/squads?team=${teamId}`;
  const res = await fetch(url, {
    headers: {
      "x-apisports-key": API_KEY,
    },
  });

  if (!res.ok) {
    console.error(`  HTTP ${res.status} for team ${teamId}`);
    return { players: [] };
  }

  const data: ApiSquadResponse = await res.json();
  const entry = data.response?.[0];
  return {
    players: entry?.players || [],
    logo: entry?.team?.logo,
  };
}

function sleep(ms: number) {
  return new Promise((r) => setTimeout(r, ms));
}

async function main() {
  // Check which teams we already have from a previous run
  const outPath = path.join(__dirname, "..", "src", "lib", "tournament", "squads-api.json");
  let existing: Record<string, unknown> = {};
  try {
    existing = JSON.parse(fs.readFileSync(outPath, "utf-8"));
  } catch { /* first run */ }

  const alreadyFetched = Object.keys(existing);
  const codes = Object.keys(TEAM_IDS).filter(c => !alreadyFetched.includes(c));

  console.log("🏟️  WC2026 Squad Updater");
  console.log(`📡 API: ${API_HOST}`);
  console.log(`⚽ Total teams: ${Object.keys(TEAM_IDS).length}`);
  console.log(`✅ Already fetched: ${alreadyFetched.length}`);
  console.log(`📥 Remaining: ${codes.length}`);
  console.log("");

  if (codes.length === 0) {
    console.log("All teams already fetched! Delete squads-api.json to re-fetch.");
    return;
  }

  const allSquads: Record<string, {
    players: {
      nameEn: string;
      num: number;
      pos: "GK" | "DEF" | "MID" | "FW";
      photo: string;
      age: number;
    }[];
    logo?: string;
  }> = existing as typeof allSquads;

  let fetched = 0;
  let failed = 0;
  const logos: Record<string, string> = {};

  for (const code of codes) {
    const teamId = TEAM_IDS[code];
    process.stdout.write(`  [${fetched + 1}/${codes.length}] ${code} (ID: ${teamId})... `);

    try {
      const { players, logo } = await fetchSquad(teamId);
      if (players.length > 0) {
        allSquads[code] = {
          players: players.map((p) => ({
            nameEn: p.name,
            num: p.number || 0,
            pos: POS_MAP[p.position] || "MID",
            photo: p.photo,
            age: p.age,
          })),
          logo,
        };
        if (logo) logos[code] = logo;
        console.log(`✅ ${players.length} players`);
      } else {
        console.log(`⚠️  no players found`);
        failed++;
      }
    } catch (e) {
      console.log(`❌ error: ${e}`);
      failed++;
    }

    fetched++;
    // Rate limit: ~1.5 request per second to be safe
    if (fetched < codes.length) await sleep(1500);
  }

  console.log("");
  console.log(`✅ Fetched: ${fetched - failed}/${codes.length}`);
  console.log(`❌ Failed: ${failed}`);
  console.log(`📊 Total in DB: ${Object.keys(allSquads).length}`);

  // Write output
  fs.writeFileSync(outPath, JSON.stringify(allSquads, null, 2), "utf-8");
  console.log(`\n💾 Saved to: ${outPath}`);

  // Generate TypeScript file with photo URLs
  const tsPath = path.join(__dirname, "..", "src", "lib", "tournament", "squad-photos.ts");
  let tsContent = `// Auto-generated by scripts/update-squads.ts\n`;
  tsContent += `// Last updated: ${new Date().toISOString()}\n\n`;
  tsContent += `export const SQUAD_PHOTOS: Record<string, Record<string, string>> = {\n`;

  for (const [code, squad] of Object.entries(allSquads)) {
    tsContent += `  ${code}: {\n`;
    const seen = new Set<string>();
    for (const p of squad.players) {
      // Handle duplicate names by appending number
      let key = p.nameEn;
      if (seen.has(key)) key = `${key} #${p.num}`;
      seen.add(key);
      tsContent += `    "${key}": "${p.photo}",\n`;
    }
    tsContent += `  },\n`;
  }
  tsContent += `};\n\n`;

  // Team logos
  tsContent += `export const TEAM_LOGOS: Record<string, string> = {\n`;
  for (const [code, logo] of Object.entries(logos)) {
    tsContent += `  ${code}: "${logo}",\n`;
  }
  tsContent += `};\n`;

  fs.writeFileSync(tsPath, tsContent, "utf-8");
  console.log(`📝 TypeScript file: ${tsPath}`);
}

main().catch(console.error);
